spans:
- seg_id: s01
  span_id: ss_qtbj_ed01_p0001_s01
  batch: qtbj_b001
- seg_id: s02
  span_id: ss_qtbj_ed01_p0001_s02
  batch: qtbj_b001
- seg_id: s03
  span_id: ss_qtbj_ed01_p0001_s03
  batch: qtbj_b001
- seg_id: s04
  span_id: ss_qtbj_ed01_p0001_s04
  batch: qtbj_b001
- seg_id: s05
  span_id: ss_qtbj_ed01_p0001_s05
  batch: qtbj_b001
- seg_id: s06
  span_id: ss_qtbj_ed01_p0001_s06
  batch: qtbj_b001
- seg_id: s07
  span_id: ss_qtbj_ed01_p0001_s07
  batch: qtbj_b001
- seg_id: s01
  span_id: ss_qtbj_ed01_p0005_s01
  batch: qtbj_b002
- seg_id: s02
  span_id: ss_qtbj_ed01_p0005_s02
  batch: qtbj_b002
- seg_id: s03
  span_id: ss_qtbj_ed01_p0005_s03
  batch: qtbj_b002
- seg_id: s04
  span_id: ss_qtbj_ed01_p0005_s04
  batch: qtbj_b002
- seg_id: s05
  span_id: ss_qtbj_ed01_p0005_s05
  batch: qtbj_b002
- seg_id: s01
  span_id: ss_qtbj_ed01_p0006_s01
  batch: qtbj_b003
- seg_id: s02
  span_id: ss_qtbj_ed01_p0006_s02
  batch: qtbj_b003
