spans:
- span_id: ss_qtbj_ed01_p0018_s01
  batch: qtbj_b012
- span_id: ss_qtbj_ed01_p0018_s02
  batch: qtbj_b012
- span_id: ss_qtbj_ed01_p0018_s03
  batch: qtbj_b012
- span_id: ss_qtbj_ed01_p0019_s01
  batch: qtbj_b013
- span_id: ss_qtbj_ed01_p0019_s02
  batch: qtbj_b013
- span_id: ss_qtbj_ed01_p0019_s03
  batch: qtbj_b013
- span_id: ss_qtbj_ed01_p0021_s01
  batch: qtbj_b014
- span_id: ss_qtbj_ed01_p0021_s02
  batch: qtbj_b014
- span_id: ss_qtbj_ed01_p0021_s03
  batch: qtbj_b014
- span_id: ss_qtbj_ed01_p0022_s01
  batch: qtbj_b015
- span_id: ss_qtbj_ed01_p0022_s02
  batch: qtbj_b015
- span_id: ss_qtbj_ed01_p0022_s03
  batch: qtbj_b015
- span_id: ss_qtbj_ed01_p0023_s01
  batch: qtbj_b016
- span_id: ss_qtbj_ed01_p0023_s02
  batch: qtbj_b016
- span_id: ss_qtbj_ed01_p0024_s01
  batch: qtbj_b017
- span_id: ss_qtbj_ed01_p0024_s02
  batch: qtbj_b017
- span_id: ss_qtbj_ed01_p0027_s01
  batch: qtbj_b018
- span_id: ss_qtbj_ed01_p0027_s02
  batch: qtbj_b018
- span_id: ss_qtbj_ed01_p0027_s03
  batch: qtbj_b018
- span_id: ss_qtbj_ed01_p0028_s01
  batch: qtbj_b019
- span_id: ss_qtbj_ed01_p0028_s02
  batch: qtbj_b019
- span_id: ss_qtbj_ed01_p0028_s03
  batch: qtbj_b019
