spans:
- span_id: ss_qtbj_ed01_p0005_s01
  batch: qtbj_b002
- span_id: ss_qtbj_ed01_p0005_s02
  batch: qtbj_b002
- span_id: ss_qtbj_ed01_p0005_s03
  batch: qtbj_b002
- span_id: ss_qtbj_ed01_p0005_s04
  batch: qtbj_b002
- span_id: ss_qtbj_ed01_p0005_s05
  batch: qtbj_b002
- span_id: ss_qtbj_ed01_p0006_s01
  batch: qtbj_b003
- span_id: ss_qtbj_ed01_p0006_s02
  batch: qtbj_b003
- span_id: ss_qtbj_ed01_p0007_s01
  batch: qtbj_b004
- span_id: ss_qtbj_ed01_p0007_s02
  batch: qtbj_b004
- span_id: ss_qtbj_ed01_p0007_s03
  batch: qtbj_b004
- span_id: ss_qtbj_ed01_p0007_s04
  batch: qtbj_b004
