spans:
- seg_id: s01
  span_id: ss_qtbj_ed01_p0007_s01
  batch: qtbj_b004
- seg_id: s02
  span_id: ss_qtbj_ed01_p0007_s02
  batch: qtbj_b004
- seg_id: s03
  span_id: ss_qtbj_ed01_p0007_s03
  batch: qtbj_b004
- seg_id: s04
  span_id: ss_qtbj_ed01_p0007_s04
  batch: qtbj_b004
- seg_id: s01
  span_id: ss_qtbj_ed01_p0008_s01
  batch: qtbj_b005
- seg_id: s02
  span_id: ss_qtbj_ed01_p0008_s02
  batch: qtbj_b005
- seg_id: s03
  span_id: ss_qtbj_ed01_p0008_s03
  batch: qtbj_b005
- seg_id: s01
  span_id: ss_qtbj_ed01_p0010_s01
  batch: qtbj_b006
- seg_id: s02
  span_id: ss_qtbj_ed01_p0010_s02
  batch: qtbj_b006
- seg_id: s03
  span_id: ss_qtbj_ed01_p0010_s03
  batch: qtbj_b006
- seg_id: s04
  span_id: ss_qtbj_ed01_p0010_s04
  batch: qtbj_b006
- seg_id: s01
  span_id: ss_qtbj_ed01_p0011_s01
  batch: qtbj_b007
- seg_id: s02
  span_id: ss_qtbj_ed01_p0011_s02
  batch: qtbj_b007
- seg_id: s03
  span_id: ss_qtbj_ed01_p0011_s03
  batch: qtbj_b007
- seg_id: s04
  span_id: ss_qtbj_ed01_p0011_s04
  batch: qtbj_b007
- seg_id: s01
  span_id: ss_qtbj_ed01_p0012_s01
  batch: qtbj_b008
- seg_id: s02
  span_id: ss_qtbj_ed01_p0012_s02
  batch: qtbj_b008
- seg_id: s03
  span_id: ss_qtbj_ed01_p0012_s03
  batch: qtbj_b008
- seg_id: s04
  span_id: ss_qtbj_ed01_p0012_s04
  batch: qtbj_b008
- seg_id: s01
  span_id: ss_qtbj_ed01_p0013_s01
  batch: qtbj_b009
- seg_id: s02
  span_id: ss_qtbj_ed01_p0013_s02
  batch: qtbj_b009
- seg_id: s01
  span_id: ss_qtbj_ed01_p0016_s01
  batch: qtbj_b010
- seg_id: s02
  span_id: ss_qtbj_ed01_p0016_s02
  batch: qtbj_b010
- seg_id: s03
  span_id: ss_qtbj_ed01_p0016_s03
  batch: qtbj_b010
- seg_id: s04
  span_id: ss_qtbj_ed01_p0016_s04
  batch: qtbj_b010
- seg_id: s01
  span_id: ss_qtbj_ed01_p0017_s01
  batch: qtbj_b011
- seg_id: s02
  span_id: ss_qtbj_ed01_p0017_s02
  batch: qtbj_b011
- seg_id: s03
  span_id: ss_qtbj_ed01_p0017_s03
  batch: qtbj_b011
- seg_id: s04
  span_id: ss_qtbj_ed01_p0017_s04
  batch: qtbj_b011
