spans:
- seg_id: s01
  span_id: ss_qtbj_ed01_p0039_s01
  batch: qtbj_b028
- seg_id: s02
  span_id: ss_qtbj_ed01_p0039_s02
  batch: qtbj_b028
- seg_id: s03
  span_id: ss_qtbj_ed01_p0039_s03
  batch: qtbj_b028
- seg_id: s01
  span_id: ss_qtbj_ed01_p0040_s01
  batch: qtbj_b029
- seg_id: s02
  span_id: ss_qtbj_ed01_p0040_s02
  batch: qtbj_b029
- seg_id: s03
  span_id: ss_qtbj_ed01_p0040_s03
  batch: qtbj_b029
- seg_id: s01
  span_id: ss_qtbj_ed01_p0042_s01
  batch: qtbj_b030
- seg_id: s02
  span_id: ss_qtbj_ed01_p0042_s02
  batch: qtbj_b030
- seg_id: s03
  span_id: ss_qtbj_ed01_p0042_s03
  batch: qtbj_b030
- seg_id: s01
  span_id: ss_qtbj_ed01_p0043_s01
  batch: qtbj_b031
- seg_id: s02
  span_id: ss_qtbj_ed01_p0043_s02
  batch: qtbj_b031
- seg_id: s03
  span_id: ss_qtbj_ed01_p0043_s03
  batch: qtbj_b031
- seg_id: s04
  span_id: ss_qtbj_ed01_p0043_s04
  batch: qtbj_b031
- seg_id: s01
  span_id: ss_qtbj_ed01_p0044_s01
  batch: qtbj_b032
- seg_id: s02
  span_id: ss_qtbj_ed01_p0044_s02
  batch: qtbj_b032
- seg_id: s03
  span_id: ss_qtbj_ed01_p0044_s03
  batch: qtbj_b032
- seg_id: s04
  span_id: ss_qtbj_ed01_p0044_s04
  batch: qtbj_b032
- seg_id: s05
  span_id: ss_qtbj_ed01_p0044_s05
  batch: qtbj_b032
- seg_id: s01
  span_id: ss_qtbj_ed01_p0045_s01
  batch: qtbj_b033
- seg_id: s02
  span_id: ss_qtbj_ed01_p0045_s02
  batch: qtbj_b033
- seg_id: s03
  span_id: ss_qtbj_ed01_p0045_s03
  batch: qtbj_b033
- seg_id: s04
  span_id: ss_qtbj_ed01_p0045_s04
  batch: qtbj_b033
- seg_id: s01
  span_id: ss_qtbj_ed01_p0048_s01
  batch: qtbj_b034
- seg_id: s02
  span_id: ss_qtbj_ed01_p0048_s02
  batch: qtbj_b034
- seg_id: s03
  span_id: ss_qtbj_ed01_p0048_s03
  batch: qtbj_b034
- seg_id: s01
  span_id: ss_qtbj_ed01_p0049_s01
  batch: qtbj_b035
- seg_id: s02
  span_id: ss_qtbj_ed01_p0049_s02
  batch: qtbj_b035
- seg_id: s03
  span_id: ss_qtbj_ed01_p0049_s03
  batch: qtbj_b035
